# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - wxciux

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies for backend
        run: |
          cd server
          npm install

      - name: Install dependencies and build frontend
        run: |
          cd client
          npm install
          npm run build
    
      - name: Verify frontend build directory
        run: |
          ls client/public

      - name: Create server/public directory
        run: |
          mkdir -p server/public

      - name: Copy frontend build to server public directory
        run: |
          robocopy client/public server/public /MIR

      - name: Print server/public directory structure for debugging
        run: |
          dir server/public /S
      
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_6871ED3461A048F9BB1E644DFDACFB1C }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_2D3737B8A0B04B5096597470F76329B9 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_031C9F89A1A8454AA606EEA99DD422A9 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        id: deploy-to-webapp
        with:
          app-name: 'wxciux'
          slot-name: 'Production'
          package: .
          
